namespace: capi-webhook-system

namePrefix: capo-

# Labels to add to all resources and selectors.
commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-openstack"

bases:
  - ../../config/crd
  - ../../config/manager
  - ../../config/webhook
  - ../../config/certmanager

patchesStrategicMerge:
  # Provide customizable hook for make targets.
  - ../../config/default/manager_image_patch.yaml
  - ../../config/default/manager_pull_policy.yaml
  # Enable webhook.
  - ../../config/default/manager_webhook_patch.yaml
  # Inject certificate in the webhook definition.
  - ../../config/default/webhookcainjection_patch.yaml

vars:
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service

patchesJson6902:
  - target:
      group: apps
      kind: Deployment
      name: controller-manager
      namespace: system
      version: v1
    path: patch_service_account.yaml